name: 'snowflake_airflow_dbt'
version: '0.21'
config-version: 2
profile: 'default'

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  snowflake_airflow_dbt:
    transform:
      schema: transform
      materialized: view
      enabled: true
    analysis:
      schema: analysis
      materialized: view
      enabled: true